repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config

template:
  org: nf-core
  name: multitme
  description: Multimodal integration
  author: Haoran Zhang
  version: 1.0.0dev
  force: true
  outdir: ./nextflow
  skip_features:
    - igenomes
    - fastqc
    - gpu
  is_nfcore: true
